services:
  web:
    image: nginx:1.25
    depends_on:
      - back
    container_name: web
    volumes:
      #- ./Maconduite_frontend/build/:/usr/share/nginx/html/
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    networks:
      - networkapp
  back:
    build: ./
    depends_on:
      - db
    container_name: back
    #command: gunicorn --bind 0.0.0.0:5000 --workers 2 "app:create_app()"
    volumes:
      - app:/etc/app
    networks:
      - networkapp
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=MICHEL
      - POSTGRES_PASSWORD=MICHELPOSTGRES
      - POSTGRES_DB=MACONDUITE
    networks:
      - networkapp
volumes:
  app:
  postgres_data:
networks:
  networkapp:
    