"""
This module provides security for the Flask application.

Specifically, it provides a session mechanism and Role-Based Access Control (or RBAC) with
JSON Web Tokens (or JWT). These tokens are encoded in the function generate_token(), and
are decoded in the decorator @auth_required.

Here is how it works : 
(1) A user makes a POST request to /auth/login/<role> with a JSON body containing its
email and password. There are only 3 roles:
- if the user is an Admin  → POST /auth/login/admin
- if the user is a Client  → POST /auth/login/client

(2) The server responds with a JSON Web Token (or access token) certifying that the user
has been authenticated with a specific role. This access token is generated by the function
generate_token().

(3) When a user makes subsequent requests to a protected route (i.e. a route that requires
authentication), he includes its access token in the JSON body of the request.

(4) The servers checks that the user is authenticated and that he's allowed to access this
protected route based on its role. This is done in the decorator @auth required.

The RBAC rules are simple:
- if the user is an Admin  → he can access all Sessions
- if the user is a Client  → he can access only his Sessions
"""